### ISSUE TITLE
not working at all 

### ISSUE THREAD

**Issue by abramas** [ferreiraklet/Jeeves#1]
i tested it with this not working

echo "http://testphp.vulnweb.com/artists.php?artist=" | qsreplace "(select(0)from(select(sleep(10)))v)" | jeeves --payload-time 10

**Comment by ferreiraklet** [comment]
Confusing ![20220405_191844.jpg](https://user-images.githubusercontent.com/90654646/161860335-0224770c-3e18-4b2c-8f74-38136364f964.jpg)

**Comment by ferreiraklet** [comment]
Gonna leave this closed, if any problems, contact again
