### ISSUE TITLE
POST request not working

### ISSUE THREAD

**Issue by S0ykot** [ferreiraklet/Jeeves#2]
Your script working on GET parameter. But what about the POST request? 

![Screenshot_2](https://user-images.githubusercontent.com/10108591/162312693-0446c7c0-1758-4690-ba88-683f97fde247.png)

**Comment by ferreiraklet** [comment]
Hey S0ykot thanks for asking
So
1. Is important to mention that jeeves takes url, he cant read requests like this
2. About the post method support, im working on it

**Comment by S0ykot** [comment]
Waiting for the POST request script.
