### ISSUE TITLE
not working error segmentation fault

### ISSUE THREAD

**Issue by abramas** [ferreiraklet/Jeeves#4]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x61972b]

goroutine 56 [running]:
main.getParams({0xc0000e8000, 0x8b}, 0x5, {0x6788da, 0x1}, {0x6788da, 0x1})
        /root/tools/Jeeves/jeeves.go:183 +0x4eb
main.main.func1()
        /root/tools/Jeeves/jeeves.go:114 +0x28c
created by main.main
        /root/tools/Jeeves/jeeves.go:91 +0x29d

**Comment by ferreiraklet** [comment]
hey man
could you send me a screenshot of your usage?

**Comment by abramas** [comment]
cat txt | Jeeves --payload-time 5

**Comment by ferreiraklet** [comment]
I did a little changing in main.go, can you reinstall it and try again?

**Comment by memmedrehimzade** [comment]
not working yet, same error

**Comment by abramas** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x61962b]

goroutine 12 [running]:
main.getParams({0xc0001623c0, 0x94}, 0x5, {0x6788da, 0x1}, {0x6788da, 0x1})
        /root/tools/Jeeves/jeeves.go:183 +0x4eb
main.main.func1()
        /root/tools/Jeeves/jeeves.go:114 +0x28c
created by main.main
        /root/tools/Jeeves/jeeves.go:91 +0x29d

**Comment by ferreiraklet** [comment]
Hey, i would like to discuss the issue in discord, could we do that?
I want to solve this issue as soon as possible
Thank you for your report

**Comment by ferreiraklet** [comment]
Sorry for any troubles guys
I now what is happening, im solving this issue ok?
Will be back with some information later.

**Comment by ferreiraklet** [comment]
Ok, I just posted a new main.go
I ask you guys for please test again
But keep in mind: Jeeves does not http probing, he cant do requests to urls that does not contain protocol ( http://, https:// )
