### ISSUE TITLE
sqlinejction in useragent

### ISSUE THREAD

**Issue by rohit0x5** [ferreiraklet/Jeeves#5]
hey  can we use sql injection payload in useragent 'XOR(if(now()=sysdate(),sleep(5*5),0))OR' this can you share the command

**Comment by ferreiraklet** [comment]
Yes, since jeeves makes his verification by the request time, you can insert payloads in header

**Comment by rohit0x5** [comment]
can you share the command for this

**Comment by ferreiraklet** [comment]
Yes man, I definitively going to put this on the new readme
